version: '3.5'

services:
  PLACEHOLDER_SERVICE_NAME:
    user: ${MY_UID}:${MY_GID}
    restart: always
    build:
      context: '.'
    image: PLACEHOLDER_IMAGE_NAME
    networks:
      - kominfo_network
    deploy:
      placement:
        constraints:
          - node.hostname == node-manager
    environment:
    - DB_CONNECTION=mysql
    - APP_DEBUG=FALSE

networks:
  kominfo_network:
    external: true
